import base64
import logging
from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel

from elevenlabs import ElevenLabs, VoiceSettings

from core.config import ELEVENLABS_API_KEY, DEFAULT_VOICE_ID
from core.models import TTSRequest, TTSResponse
from core.security import get_current_user

logger = logging.getLogger(__name__)

eleven_client = ElevenLabs(api_key=ELEVENLABS_API_KEY)
router = APIRouter(tags=['tts'])

# Server-side cache for sound-effect generations so we don't burn ElevenLabs
# credits regenerating identical ambient prompts for every device. Keyed by
# (text, duration_seconds, loop) and stores the base64 mp3 once produced.
_SOUND_EFFECT_CACHE: dict[tuple, str] = {}


class SoundEffectRequest(BaseModel):
    text: str
    duration_seconds: float | None = None
    loop: bool | None = False
    prompt_influence: float | None = 0.3


class SoundEffectResponse(BaseModel):
    audio_base64: str
    mime_type: str = 'audio/mpeg'


@router.post('/tts/generate', response_model=TTSResponse)
async def generate_tts(
    payload: TTSRequest,
    current_user: dict = Depends(get_current_user),
):
    try:
        audio_iter = eleven_client.text_to_speech.convert(
            text=payload.text,
            voice_id=DEFAULT_VOICE_ID,
            model_id='eleven_multilingual_v2',
            output_format='mp3_44100_128',
            voice_settings=VoiceSettings(
                stability=0.6,
                similarity_boost=0.75,
                style=0.2,
                use_speaker_boost=True,
            ),
        )
        audio_bytes = b''.join(audio_iter)
        b64 = base64.b64encode(audio_bytes).decode('utf-8')
        return TTSResponse(audio_base64=b64, mime_type='audio/mpeg')
    except Exception as e:
        logger.error(f'TTS failed: {e}')
        raise HTTPException(status_code=500, detail='Voice generation failed')


@router.post('/tts/sound-effect', response_model=SoundEffectResponse)
async def generate_sound_effect(payload: SoundEffectRequest):
    """
    Public endpoint (no auth) used by the splash screen to fetch an ambient
    sound generated by ElevenLabs Sound Generation. Result is cached
    server-side per (text, duration, loop) so every device pulls the same
    bytes after the first call. The frontend then caches the bytes locally.
    """
    cache_key = (payload.text.strip(), payload.duration_seconds or 0, bool(payload.loop))
    cached = _SOUND_EFFECT_CACHE.get(cache_key)
    if cached:
        return SoundEffectResponse(audio_base64=cached)

    try:
        kwargs: dict = {
            'text': payload.text,
            'output_format': 'mp3_44100_128',
            'prompt_influence': payload.prompt_influence or 0.3,
        }
        if payload.duration_seconds is not None:
            kwargs['duration_seconds'] = payload.duration_seconds
        if payload.loop:
            kwargs['loop'] = True

        audio_iter = eleven_client.text_to_sound_effects.convert(**kwargs)
        audio_bytes = b''.join(audio_iter)
        b64 = base64.b64encode(audio_bytes).decode('utf-8')
        _SOUND_EFFECT_CACHE[cache_key] = b64
        return SoundEffectResponse(audio_base64=b64)
    except Exception as e:
        logger.error(f'Sound effect generation failed: {e}')
        raise HTTPException(status_code=500, detail='Sound generation failed')
