import base64
import io
import logging
from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel

from elevenlabs import ElevenLabs, VoiceSettings

from core.config import ELEVENLABS_API_KEY, DEFAULT_VOICE_ID
from core.models import TTSRequest, TTSResponse
from core.security import get_current_user

logger = logging.getLogger(__name__)

eleven_client = ElevenLabs(api_key=ELEVENLABS_API_KEY)
router = APIRouter(tags=['tts'])

# Server-side cache for sound-effect generations so we don't burn ElevenLabs
# credits regenerating identical ambient prompts for every device. Keyed by
# (text, duration_seconds, loop) and stores the base64 mp3 once produced.
_SOUND_EFFECT_CACHE: dict[tuple, str] = {}


class SoundEffectRequest(BaseModel):
    text: str
    duration_seconds: float | None = None
    loop: bool | None = False
    prompt_influence: float | None = 0.3


class SoundEffectResponse(BaseModel):
    audio_base64: str
    mime_type: str = 'audio/mpeg'


class STTRequest(BaseModel):
    audio_base64: str
    language_code: str | None = None  # e.g. "en"
    file_format_hint: str | None = None  # e.g. "audio/m4a"


class STTResponse(BaseModel):
    text: str


@router.post('/tts/generate', response_model=TTSResponse)
async def generate_tts(
    payload: TTSRequest,
    current_user: dict = Depends(get_current_user),
):
    try:
        audio_iter = eleven_client.text_to_speech.convert(
            text=payload.text,
            voice_id=DEFAULT_VOICE_ID,
            model_id='eleven_multilingual_v2',
            output_format='mp3_44100_128',
            voice_settings=VoiceSettings(
                stability=0.6,
                similarity_boost=0.75,
                style=0.2,
                use_speaker_boost=True,
            ),
        )
        audio_bytes = b''.join(audio_iter)
        b64 = base64.b64encode(audio_bytes).decode('utf-8')
        return TTSResponse(audio_base64=b64, mime_type='audio/mpeg')
    except Exception as e:
        logger.error(f'TTS failed: {e}')
        raise HTTPException(status_code=500, detail='Voice generation failed')


@router.post('/tts/sound-effect', response_model=SoundEffectResponse)
async def generate_sound_effect(payload: SoundEffectRequest):
    """
    Public endpoint (no auth) used by the splash screen to fetch an ambient
    sound generated by ElevenLabs Sound Generation. Result is cached
    server-side per (text, duration, loop) so every device pulls the same
    bytes after the first call. The frontend then caches the bytes locally.
    """
    cache_key = (payload.text.strip(), payload.duration_seconds or 0, bool(payload.loop))
    cached = _SOUND_EFFECT_CACHE.get(cache_key)
    if cached:
        return SoundEffectResponse(audio_base64=cached)

    try:
        kwargs: dict = {
            'text': payload.text,
            'output_format': 'mp3_44100_128',
            'prompt_influence': payload.prompt_influence or 0.3,
        }
        if payload.duration_seconds is not None:
            kwargs['duration_seconds'] = payload.duration_seconds
        if payload.loop:
            kwargs['loop'] = True

        audio_iter = eleven_client.text_to_sound_effects.convert(**kwargs)
        audio_bytes = b''.join(audio_iter)
        b64 = base64.b64encode(audio_bytes).decode('utf-8')
        _SOUND_EFFECT_CACHE[cache_key] = b64
        return SoundEffectResponse(audio_base64=b64)
    except Exception as e:
        logger.error(f'Sound effect generation failed: {e}')
        raise HTTPException(status_code=500, detail='Sound generation failed')


@router.post('/tts/transcribe', response_model=STTResponse)
async def transcribe_audio(
    payload: STTRequest,
    current_user: dict = Depends(get_current_user),
):
    """Speech-to-Text — accepts a base64-encoded audio recording (m4a / mp4 /
    wav etc.) from the client and returns transcribed text via ElevenLabs
    Scribe. Used by the Home tab's microphone input for voice-first users."""
    try:
        try:
            audio_bytes = base64.b64decode(payload.audio_base64)
        except Exception:
            raise HTTPException(status_code=400, detail='Invalid base64 audio')

        if len(audio_bytes) < 200:
            raise HTTPException(status_code=400, detail='Recording too short')

        bio = io.BytesIO(audio_bytes)
        bio.name = 'recording.m4a'  # ElevenLabs uses extension to detect format

        kwargs: dict = {
            'model_id': 'scribe_v1',
            'file': bio,
            'tag_audio_events': False,
        }
        if payload.language_code:
            kwargs['language_code'] = payload.language_code

        result = eleven_client.speech_to_text.convert(**kwargs)
        text = getattr(result, 'text', None) or ''
        if isinstance(text, str):
            text = text.strip()
        return STTResponse(text=text)
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f'STT failed: {e}')
        raise HTTPException(status_code=500, detail='Transcription failed')
